config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :coins, only: [:show]
  resources :predictions, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin.rb
# == Schema Information
#
# Table name: coins
#
#  id                 :integer          not null, primary key
#  name               :string
#  uid                :integer
#  symbol             :string
#  website_slug       :string
#  circulating_supply :float
#  total_supply       :float
#  max_supply         :float
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class Coin < ApplicationRecord
  has_many :ticks
  has_many :predictions

  validates :name, :uid, :symbol, :website_slug,
            :circulating_supply, :total_supply, presence: true

  def create_tick(data)
    ticks.create!(
      price: data['price'],
      daily_volume: data['volume_24h'],
      market_cap: data['market_cap'],
      hourly_change: data['percent_change_1h'],
      daily_change: data['percent_change_24h'],
      weekly_change: data['percent_change_7d'],
      rank: data['rank']
    )
  end

  def self.find_or_create_from_service(data)
    find_or_create_by!(uid: data['id']) do |coin|
      coin.name = data['name']
      coin.symbol = data['symbol']
      coin.website_slug = data['website_slug']
      coin.circulating_supply = data['circulating_supply']
      coin.total_supply = data['total_supply']
      coin.max_supply = data['max_supply']
    end
  end
end

app/models/prediction.rb
# == Schema Information
#
# Table name: predictions
#
#  id                   :integer          not null, primary key
#  coin_id              :integer
#  tick_id              :integer
#  timeframe            :date
#  original_price       :float
#  highest_price_so_far :float
#  successful           :boolean          default("false")
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#
# Indexes
#
#  index_predictions_on_coin_id  (coin_id)
#  index_predictions_on_tick_id  (tick_id)
#

class Prediction < ApplicationRecord
  PREDICTION_DAYS = 5
  CONSECUTIVE_DAILY_VOLUMES = 5

  belongs_to :coin
  belongs_to :responsible_tick, class_name: 'Tick', foreign_key: :tick_id

  before_validation :set_timeframe
  validates :timeframe, :original_price, :highest_price_so_far, presence: true

  scope :active, -> { where('timeframe > ?', Time.zone.now) }

  def update_price_so_far(price)
    update!(highest_price_so_far: price) if price > highest_price_so_far
  end

  def change_so_far
    ((highest_price_so_far - original_price)/original_price)*100
  end

  def self.create_if_conditions_match(tick)
    # Condition: if daily volume grows for 5 ticks (hours in a row)

    coin = tick.coin
    last_daily_volumes = coin.ticks.order_desc.limit(CONSECUTIVE_DAILY_VOLUMES).pluck(:daily_volume)

    if last_daily_volumes.sort.reverse == last_daily_volumes
      create!(responsible_tick: tick, coin: coin, original_price: tick.price, highest_price_so_far: tick.price)
    end
  end

  private

  def set_timeframe
    self.timeframe = PREDICTION_DAYS.days.from_now
  end
end

app/models/tick.rb
# == Schema Information
#
# Table name: ticks
#
#  id            :integer          not null, primary key
#  coin_id       :integer
#  price         :float
#  daily_volume  :float
#  market_cap    :float
#  hourly_change :float
#  daily_change  :float
#  weekly_change :float
#  rank          :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
# Indexes
#
#  index_ticks_on_coin_id  (coin_id)
#

class Tick < ApplicationRecord
  belongs_to :coin

  validates :price, :daily_volume, :market_cap, :hourly_change,
            :daily_change, :weekly_change, :rank, presence: true

  after_create :update_predictions

  scope :latest, -> { where(id: Tick.order(id: :desc).limit(100)) }
  scope :order_desc, -> { order(id: :desc) }
  scope :with_coin, -> { includes(:coin) }

  scope :hourly_top, -> { latest.order(hourly_change: :desc).limit(10) }
  scope :daily_top, -> { latest.order(daily_change: :desc).limit(10) }
  scope :weekly_top, -> { latest.order(weekly_change: :desc).limit(10) }

  def self.delete_old_ticks
    where('created_at < ?', 5.days.ago).destroy_all
  end

  private

  def update_predictions
    existing_prediction = coin.predictions.active.first

    if existing_prediction
      existing_prediction.update_price_so_far(price)
    else
      Prediction.create_if_conditions_match(self)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  helper_method :coin

  def show
  end

  private

  def coin
    @coin ||= Coin.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @hourly_top_ticks = Tick.hourly_top.with_coin
    @daily_top_ticks = Tick.daily_top.with_coin
    @weekly_top_ticks = Tick.weekly_top.with_coin
  end
end

app/controllers/predictions_controller.rb
class PredictionsController < ApplicationController

  def index
    @predictions = Prediction.active.includes(:coin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/coins/show.haml
%h2= coin.name

%table.table
  %thead
    %th ID
    %th Date
    %th Price
    %th Daily volume
    %th Market cap
    %th Rank

  %tbody
    - coin.ticks.order_desc.each do |tick|
      %tr
        %td= tick.id
        %td= tick.created_at
        %td= tick.price
        %td= tick.daily_volume
        %td= tick.market_cap
        %td= tick.rank

app/views/home/index.haml
%h2 Hourly top
%ol
  - @hourly_top_ticks.each do |tick|
    %li= link_to(tick.coin.name, coin_path(tick.coin)) + " | +#{tick.hourly_change}%"

%h2 Daily top
%ol
  - @daily_top_ticks.each do |tick|
    %li= link_to(tick.coin.name, coin_path(tick.coin)) + " | +#{tick.daily_change}%"

%h2 Weekly top
%ol
  - @weekly_top_ticks.each do |tick|
    %li= link_to(tick.coin.name, coin_path(tick.coin)) + " | +#{tick.weekly_change}%"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoPredictor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1><%= link_to 'CryptoPredictor', '/' %></h1>
    </header>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'Home', '/', class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'Current predictions', predictions_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/predictions/index.haml
%h2 Active predictions

%table.table
  %thead
    %th ID
    %th Coin
    %th Created at
    %th Original price
    %th High point
    %th Timeframe

  %tbody
    - @predictions.each do |prediction|
      %tr
        %td= prediction.id
        %td= prediction.coin.name
        %td= prediction.created_at
        %td= prediction.original_price
        %td
          = prediction.highest_price_so_far
          - change = prediction.change_so_far
          %span{ class: change > 0 ? 'change-indicator increase' : 'change-indicator decrease' }
            = number_to_percentage(change, precision: 2)
        %td= prediction.timeframe